#!/usr/bin/env node
// Concatenates every component module into components/bundle.js so the page loads 1 module instead of 693.
// Zero dependencies. Each source file is wrapped in its own function scope (top-level helpers can't
// collide) and in try/catch (one component throwing at import time is skipped, like a failed category).
// The per-file modules stay deployed: they are the fallback, the dev path, and what long-press copies.
//   node scripts/build.mjs          write components/bundle.js
//   node scripts/build.mjs --check  exit 1 if components/bundle.js is stale (for validate / CI)
import { readFileSync, writeFileSync, existsSync, renameSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'components/bundle.js');
const { CATEGORIES } = await import(pathToFileURL(join(ROOT, 'components/manifest.js')).href);

const hash = createHash('sha256');
let body = '';
const cats = {};
const sources = {};
let n = 0;
for (const c of CATEGORIES) {
  const idx = readFileSync(join(ROOT, 'components', c, 'index.js'), 'utf8');
  hash.update(`components/${c}/index.js\0` + idx + '\0'); // membership and order come from index.js
  const files = [...idx.matchAll(/from\s+['"]\.\/([^'"]+)['"]/g)].map((m) => m[1]);
  cats[c] = [];
  for (const f of files) {
    const rel = `components/${c}/${f}`;
    const src = readFileSync(join(ROOT, rel), 'utf8');
    hash.update(rel + '\0' + src + '\0');
    if ((src.match(/^export default /gm) || []).length !== 1 || /^\s*(import|export)\s(?!default )/m.test(src)) {
      throw new Error(`${rel}: expected one top-level "export default" and no other import/export (CONTRACT rule 1)`);
    }
    const name = `c${n++}`;
    body += `// ${rel}\nconst ${name} = (() => { let __default; try {\n${src.replace(/^export default /m, '__default = ')}\n;} catch (err) { console.error('[buttons] ${rel} failed', err); return null; } return __default; })();\n`;
    cats[c].push(name);
  }
}
const digest = hash.digest('hex').slice(0, 16);
const out = `// GENERATED by scripts/build.mjs — do not edit. source-hash: ${digest}\n${body}\n` +
  `export default {\n${CATEGORIES.map((c) => `  ${JSON.stringify(c)}: [${cats[c].join(', ')}],`).join('\n')}\n};\n`;

if (process.argv.includes('--check')) {
  const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8').match(/source-hash: (\w+)/)?.[1] : null;
  if (cur !== digest) { console.error(`components/bundle.js is stale (have ${cur}, want ${digest}); run: node scripts/build.mjs`); process.exit(1); }
  console.log('bundle up to date'); process.exit(0);
}
const TMP = OUT.replace(/\.js$/, '.tmp.js');
writeFileSync(TMP, out);
const mod = await import(pathToFileURL(TMP).href + '?t=' + Date.now()); // sanity: the bundle parses and evaluates in Node (CONTRACT rule 2)
const total = Object.values(mod.default).reduce((s, l) => s + l.filter(Boolean).length, 0);
if (total !== n) throw new Error(`bundle evaluated ${total} of ${n} components`);
renameSync(TMP, OUT); // only a bundle that evaluated replaces the old one
console.log(`components/bundle.js: ${n} components, ${(out.length / 1024).toFixed(0)} KiB, hash ${digest}`);
